spring:
  application:
    name: microservice-provider123
  zipkin:
    base-url: http://localhost:9412
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq: #配置mq消息队列
    host: 192.168.2.105 
    port: 5672 
    username: admin 
    password: admin
server:
  port: 7906
eureka:
  instance:
    hostname: localhost   # 指定该Eureka实例的主机名
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka
